/* One reusable account profile view. SELF is the signed-in account; ADMIN_VIEW is selected from accounts. */
(function (A) {
  'use strict';
  const U = A.U, ui = A.ui;
  const AS = () => A.features.accounts.service;
  const TABS = [['info', 'Thông tin cá nhân'], ['access', 'Phân quyền & phạm vi'], ['security', 'Bảo mật tài khoản']];
  const STATUS = { ACTIVE: ['Đang hoạt động', 'ok'], PENDING_ACTIVATION: ['Chờ kích hoạt', 'warn'], LOCKED: ['Tạm khóa', 'danger'] };
  const initials = name => { const w = String(name || '').trim().split(/\s+/).filter(Boolean); return ((w[0] || '')[0] || '') + (w.length > 1 ? (w[w.length - 1][0] || '') : ''); };
  const statusTag = acc => { const x = STATUS[A.ACCOUNTS.authStatus(acc)] || STATUS.LOCKED; return `<span class="tag ${x[1]}"><span class="profile-status-dot"></span>${x[0]}</span>`; };
  const fieldList = rows => `<div class="profile-fields">${rows.filter(Boolean).map(r => `<div class="profile-field"><div class="profile-field-label">${r[0]}</div><div class="profile-field-value">${r[1]}</div></div>`).join('')}</div>`;
  const card = (title, icon, body, cls) => `<section class="card profile-card ${cls || ''}"><h3>${U.icon(icon)}${title}</h3>${body}</section>`;
  const fmtTime = iso => { const d = new Date(iso); return isNaN(d) ? '' : U.dmy(d.toISOString().slice(0, 10)) + ' ' + String(d.getHours()).padStart(2, '0') + ':' + String(d.getMinutes()).padStart(2, '0'); };
  const requests = () => { A.db.phoneChangeRequests = Array.isArray(A.db.phoneChangeRequests) ? A.db.phoneChangeRequests : []; return A.db.phoneChangeRequests; };
  const reqLabel = s => ({ PENDING: 'Chờ xử lý', APPROVED_PENDING_OTP: 'Chờ xác minh số mới', REJECTED: 'Đã từ chối', COMPLETED: 'Đã hoàn tất', CANCELLED: 'Đã hủy' })[s] || s;
  const reqTag = r => `<span class="tag ${r.status === 'REJECTED' ? 'danger' : r.status === 'COMPLETED' ? 'ok' : 'warn'}">${reqLabel(r.status)}</span>`;
  const mask = phone => U.maskPhone(phone || '');
  const phoneOk = phone => /^0\d{9}$/.test(A.ACCOUNTS.normalizePhone(phone));
  const notify = (accountId, title, body) => { A.db.notifications = A.db.notifications || []; A.db.notifications.unshift({ id: 'TB-' + U.pad(32 + A.db.notifications.length, 3), at: U.today(), title, body, accountId, group: 'Tài khoản người dùng', channels: ['Trong hệ thống'], sent: 1, delivered: 1, read: 0, auto: true, kind: 'PHONE_CHANGE' }); if (A.personalNotifications) { const recipients = accountId ? [accountId] : A.ACCOUNTS.list().filter(a => A.ACCOUNTS.primaryRole(a) === 'system_admin').map(a => a.id); recipients.forEach(id => A.personalNotifications.add({ recipientAccountId: id, type: 'PHONE_CHANGE', title, message: body, targetRoute: id === accountId ? 'thong-tin-ca-nhan' : 'tai-khoan' })); } };
  const ownRequest = p => requests().find(r => r.accountId === p.acc.id && ['PENDING', 'APPROVED_PENDING_OTP'].includes(r.status));

  function resolve() {
    const viewer = A.currentAccount();
    if (!viewer) return null;
    // An ADMIN_VIEW belongs to the viewer that opened it. If the demo/login account changes,
    // fall back safely to SELF instead of leaking the previous viewer's selected record.
    const chosen = ui.profile && ui.profile.mode === 'admin' && ui.profile.viewerId === viewer.id && U.can('tai-khoan') ? A.ACCOUNTS.get(ui.profile.accountId) : null;
    const acc = chosen || viewer, roleId = A.ACCOUNTS.primaryRole(acc), role = A.PERM.role(roleId);
    const trader = acc.traderId && A.idx && A.idx.trader ? A.idx.trader.get(acc.traderId) : null;
    const global = (acc.marketScopes || []).includes('ALL'), markets = A.allowedMarkets(acc).map(id => U.market(id)).filter(Boolean);
    return { acc, viewer, mode: chosen ? 'ADMIN_VIEW' : 'SELF', roleId, roleName: role ? role.name : (roleId || 'Chưa gán'), trader,
      kind: AS().userKind(acc), name: (trader && trader.name) || acc.fullName, phone: (trader && trader.phone) || acc.phone || '', global, markets,
      scopeLabel: global ? 'Tất cả chợ' : markets.length ? markets.map(m => m.short).join(', ') : 'Chưa phân công' };
  }
  function avatarSource(p) { const t = p.trader && p.trader.docFiles && p.trader.docFiles.avatar; return (t && t.dataUrl) || (p.acc.avatar && p.acc.avatar.dataUrl) || ''; }
  function avatarHtml(p) { const src = avatarSource(p); return `<div class="profile-avatar-wrap"><span class="profile-avatar ${src ? 'has-photo' : ''}">${src ? `<img src="${U.esc(src)}" alt="">` : U.esc(initials(p.name).toUpperCase())}</span>${p.mode === 'SELF' ? '<button class="profile-avatar-action" data-act="profile-avatar-open" title="Đổi ảnh đại diện" aria-label="Đổi ảnh đại diện">' + U.icon('camera') + '</button>' : ''}</div>`; }
  function headerHtml(p) {
    const sub = p.kind === 'trader' ? 'Tiểu thương' : (p.acc.organization || '');
    const action = p.mode === 'SELF' ? `<button class="btn primary" data-act="profile-edit-open">${U.icon('edit')}Chỉnh sửa thông tin</button>` : (A.canDo('tai-khoan.sua') ? `<button class="btn primary" data-act="profile-admin-edit" data-id="${p.acc.id}">${U.icon('edit')}Chỉnh sửa tài khoản</button>` : '');
    return `<section class="card profile-summary"><div class="profile-summary-main">${avatarHtml(p)}<div class="profile-identity"><div class="profile-name-row"><h2 class="profile-name">${U.esc(p.name)}</h2>${action}</div><div class="profile-role-status"><span class="profile-role">${U.esc(p.roleName)}</span>${statusTag(p.acc)}</div><div class="profile-contact-line">${p.phone ? `${U.icon('phone')}${U.esc(p.phone)}` : ''}${sub ? `${p.phone ? '<span class="profile-contact-sep">·</span>' : ''}${U.esc(sub)}` : ''}</div><div class="profile-summary-meta"><span><small>Mã tài khoản:</small><b>${U.esc(p.acc.code)}</b></span><span><small>${U.esc(AS().USER_KIND[p.kind])}</small></span><span><small>Phạm vi:</small><b>${U.esc(p.scopeLabel)}</b></span></div></div></div></section>`;
  }
  function personalRows(p) { const t = p.trader; return p.kind === 'trader' ? [['Họ và tên', `<b>${U.esc(p.name)}</b>`], ['Số điện thoại đăng nhập', p.phone ? U.esc(p.phone) : 'Chưa cập nhật'], t && t.gender ? ['Giới tính', U.esc(t.gender)] : null, t && t.birth ? ['Năm sinh', U.esc(String(t.birth))] : null, t ? ['Mã tiểu thương', `<b>${U.esc(t.id)}</b>`] : null] : [['Họ và tên', `<b>${U.esc(p.name)}</b>`], ['Ngày sinh', p.acc.dateOfBirth ? U.dmy(p.acc.dateOfBirth) : 'Chưa cập nhật'], ['Giới tính', p.acc.gender || 'Chưa cập nhật'], ['Địa chỉ', p.acc.address || 'Chưa cập nhật'], ['Số điện thoại đăng nhập', p.phone ? U.esc(p.phone) : 'Chưa cập nhật'], p.acc.title ? ['Chức vụ', U.esc(p.acc.title)] : null, ['Đơn vị công tác', p.acc.organization ? U.esc(p.acc.organization) : 'Chưa cập nhật']]; }
  function accountRows(p) { return [['Mã tài khoản', `<b>${U.esc(p.acc.code)}</b>`], ['Loại người dùng', AS().USER_KIND[p.kind]], ['Vai trò', U.esc(p.roleName)], ['Trạng thái', statusTag(p.acc)], p.acc.lastLoginAt ? ['Đăng nhập gần nhất', fmtTime(p.acc.lastLoginAt)] : null]; }
  function scopeCard(p) { const body = p.global ? '<div class="profile-scope-chips"><span class="tag info">Tất cả chợ</span></div><p>Bạn được cấp quyền truy cập tất cả các chợ trong hệ thống.</p>' : p.markets.length ? `<div class="profile-scope-chips">${p.markets.map(m => `<span class="tag info">${U.esc(m.name)}</span>`).join('')}</div><p>${p.markets.length === 1 ? 'Bạn được cấp quyền truy cập chợ này.' : `Bạn được cấp quyền truy cập ${p.markets.length} chợ.`}</p>` : '<p>Tài khoản chưa được phân công chợ nào.</p>'; return card('Phạm vi truy cập', 'bank', body, 'profile-scope-card'); }
  function phonePanel(p) { const r = ownRequest(p); if (!r) return `<div class="profile-field profile-phone-panel"><div class="profile-field-label">Số điện thoại đăng nhập</div><div class="profile-field-value">${U.esc(p.phone || 'Chưa cập nhật')}</div><small>Số điện thoại này được sử dụng để đăng nhập và nhận mã OTP.</small>${p.mode === 'SELF' ? '<button class="btn sm" data-act="phone-change-open">Yêu cầu thay đổi</button>' : ''}</div>`; const action = r.status === 'APPROVED_PENDING_OTP' && p.mode === 'SELF' ? '<button class="btn sm primary" data-act="phone-change-verify" data-id="' + r.id + '">Xác minh số điện thoại mới</button>' : '<button class="btn sm" data-act="phone-change-detail" data-id="' + r.id + '">Xem yêu cầu</button>'; return `<div class="profile-field profile-phone-panel"><div class="profile-field-label">Số điện thoại đăng nhập</div><div class="profile-field-value">${U.esc(p.phone || 'Chưa cập nhật')}</div><div class="small">⏱ Yêu cầu thay đổi sang ${U.esc(mask(r.newPhone))} · ${reqTag(r)}</div>${action}</div>`; }
  function infoTab(p) { return `<div class="profile-grid"><div>${card('Thông tin cá nhân', 'users', fieldList(personalRows(p)))}</div><div class="profile-right-column">${card('Thông tin tài khoản', 'file', fieldList(accountRows(p)))}${scopeCard(p)}</div></div>`; }
  function accessTab(p) {
    const granted = new Set(A.PERM.rolePermKeys(p.roleId));
    const screens = A.PERM.catalog().filter(x => x.kind === 'screen' && granted.has(x.key)), actions = A.PERM.catalog().filter(x => x.kind === 'action' && granted.has(x.key));
    const listed = screens.length ? `<ul class="profile-access-list">${screens.map(s => { const acts = actions.filter(a => a.screenId === s.screenId); return `<li><span class="profile-check">✓</span><div><b>${U.esc(s.label)}</b><small>${acts.length ? acts.map(a => U.esc(a.label)).join(' · ') : 'Xem'}</small></div></li>`; }).join('')}</ul>` : '<p class="muted small">Tài khoản chưa được cấp quyền truy cập màn hình nào.</p>';
    const note = p.mode === 'SELF' ? 'Vai trò và phạm vi do Quản trị hệ thống phân công; bạn không thể tự thay đổi tại đây.' : 'Vai trò và phạm vi hiển thị theo cấu hình phân quyền hiện hành của tài khoản.';
    return `<div class="profile-grid"><div>${card('Vai trò hiện tại', 'users', fieldList([['Vai trò', `<b>${U.esc(p.roleName)}</b>`], ['Phạm vi', U.esc(p.scopeLabel)]]) + `<p class="profile-card-note">${note}</p>`)}</div><div>${scopeCard(p)}</div></div>${card('Quyền truy cập hiệu lực', 'check', listed)}`;
  }
  function securityRequest(p) {
    const r = ownRequest(p);
    if (!r) return p.mode === 'SELF' ? '<button class="btn sm primary profile-phone-request-action" data-act="phone-change-open">Yêu cầu thay đổi số điện thoại</button>' : '';
    const approved = r.status === 'APPROVED_PENDING_OTP';
    const action = approved && p.mode === 'SELF'
      ? `<button class="btn sm primary" data-act="phone-change-verify" data-id="${r.id}">Xác minh số điện thoại mới</button>`
      : `<button class="btn sm" data-act="phone-change-detail" data-id="${r.id}">Xem yêu cầu</button>`;
    return `<div class="profile-phone-request"><div class="profile-phone-request-head"><b>Yêu cầu thay đổi số điện thoại</b>${reqTag(r)}</div><div class="profile-phone-request-meta"><span>Số mới: <b>${U.esc(mask(r.newPhone))}</b></span><span>Ngày gửi: ${fmtTime(r.requestedAt)}</span></div>${action}</div>`;
  }
  function securityTab(p) {
    const phoneCard = card('Số điện thoại đăng nhập', 'phone', `<p class="profile-security-desc">Số điện thoại này được sử dụng để đăng nhập và nhận mã OTP.</p><div class="profile-login-number"><b>${U.esc(p.phone || 'Chưa cập nhật')}</b><span>🔒 Không thể chỉnh sửa</span></div>${securityRequest(p)}`, 'profile-login-card');
    const methodCard = card('Phương thức đăng nhập', 'phone', `<div class="profile-login-method"><b>Số điện thoại + mã OTP</b><p>Đăng nhập bằng số điện thoại và xác thực qua mã OTP.</p></div>`, 'profile-method-card');
    const s = p.mode === 'SELF' && ui.sessionMetadata && ui.sessionMetadata.accountId === p.acc.id ? ui.sessionMetadata : null;
    const sessionRows = [['Thiết bị', s && s.device ? s.device : 'Chưa ghi nhận'], ['Trình duyệt', s && s.browser ? s.browser : 'Chưa ghi nhận'], ['Địa điểm', s && s.locationLabel ? s.locationLabel : 'Chưa ghi nhận'], ['Thời gian', s && s.loginAt ? fmtTime(s.loginAt) : 'Chưa ghi nhận']];
    const sessionCard = card('Phiên đăng nhập hiện tại', 'file', `<div class="profile-session-fields">${sessionRows.map(r => `<div class="profile-session-field"><span>${r[0]}</span><b>${U.esc(r[1])}</b></div>`).join('')}</div>`, 'profile-session-card');
    return `<div class="profile-security-grid"><div class="profile-security-main">${phoneCard}</div><div class="profile-security-side">${methodCard}${sessionCard}</div></div>`;
  }
  function editModal(p) { const staff = p.kind !== 'trader'; const staffFields = staff ? `<div class="profile-edit-section">Thông tin cơ bản</div><div class="form-grid"><div class="field"><label>Ngày sinh</label><input id="profile-edit-birth" type="date" class="input" value="${U.esc(p.acc.dateOfBirth || '')}"></div><div class="field"><label>Giới tính</label><select id="profile-edit-gender" class="input"><option value="">Chưa cập nhật</option>${['Nam','Nữ','Khác'].map(x => `<option ${p.acc.gender === x ? 'selected' : ''}>${x}</option>`).join('')}</select></div></div><div class="field"><label>Địa chỉ</label><textarea id="profile-edit-address" class="input" rows="2">${U.esc(p.acc.address || '')}</textarea></div>` : ''; return A.mHead('Chỉnh sửa thông tin cá nhân') + `<div class="modal-b profile-edit-modal"><div class="profile-edit-section">Thông tin cơ bản</div><div class="field"><label>Họ và tên *</label><input id="profile-edit-name" class="input" value="${U.esc(p.name)}"></div>${staffFields}<div class="profile-edit-section">Số điện thoại đăng nhập</div><div class="profile-login-phone"><b>${U.esc(p.phone)}</b><span>🔒</span><small>Số điện thoại được sử dụng để đăng nhập và nhận mã OTP.</small><button class="btn sm" data-act="phone-change-open">Yêu cầu thay đổi số điện thoại</button></div></div><div class="modal-f"><button class="btn" data-act="close">Hủy</button><button class="btn primary" data-act="profile-edit-save">Lưu thay đổi</button></div>`; }
  function avatarModal(draft) { return A.mHead('Chọn ảnh đại diện') + `<div class="modal-b profile-avatar-modal">${draft ? `<img src="${U.esc(draft.dataUrl)}" alt="Xem trước ảnh đại diện" class="profile-avatar-preview"><p class="small muted">${U.esc(draft.name)}</p>` : '<div class="profile-avatar-empty">Chọn ảnh JPG, JPEG, PNG hoặc WEBP (tối đa 1 MB).</div>'}</div><div class="modal-f"><button class="btn" data-act="close">Hủy</button>${draft ? '<button class="btn primary" data-act="profile-avatar-save">Lưu ảnh</button>' : '<button class="btn primary" data-act="profile-avatar-choose">Chọn ảnh</button>'}</div>`; }
  function openProfile(accountId) { ui.profile = accountId ? { mode: 'admin', accountId, viewerId: A.currentAccount().id, tab: 'info' } : { mode: 'self', accountId: null, tab: 'info' }; A.go('thong-tin-ca-nhan'); }
  A.openAccountProfile = function (accountId) { if (!U.can('tai-khoan') || !A.ACCOUNTS.get(accountId)) return; openProfile(accountId); };
  A.VIEWS['thong-tin-ca-nhan'] = function () { const p = resolve(); if (!p) return '<div class="empty">Không xác định được tài khoản đang đăng nhập.</div>'; const tab = TABS.some(x => x[0] === (ui.profile && ui.profile.tab)) ? ui.profile.tab : 'info', back = p.mode === 'ADMIN_VIEW' ? '<div class="profile-page-head"><button class="profile-back" data-act="profile-back-accounts">← Tài khoản người dùng</button></div>' : '', body = tab === 'access' ? accessTab(p) : tab === 'security' ? securityTab(p) : infoTab(p); return `<div class="profile-page">${back}${headerHtml(p)}<div class="profile-tabs" role="tablist">${TABS.map(x => `<button role="tab" aria-selected="${tab === x[0]}" class="${tab === x[0] ? 'on' : ''}" data-act="profile-tab" data-id="${x[0]}">${x[1]}</button>`).join('')}</div>${body}</div>`; };
  A.ACT['profile-tab'] = el => { ui.profile = ui.profile || {}; ui.profile.tab = el.dataset.id; A.render(); };
  A.ACT['profile-back-accounts'] = () => { ui.profile = null; A.go('tai-khoan'); };
  A.ACT['profile-admin-edit'] = el => { if (A.canDo('tai-khoan.sua')) A.ACT['acc-edit'](el); };
  A.ACT['profile-edit-open'] = () => { const p = resolve(); if (p && p.mode === 'SELF') A.modal(editModal(p)); };
  A.ACT['profile-edit-save'] = () => { const p = resolve(); if (!p || p.mode !== 'SELF') return; const name = (A.$('#profile-edit-name').value || '').trim(); if (!name) { U.toast('Vui lòng nhập họ và tên.'); return; } if (p.trader) { p.trader.name = name; A.ACCOUNTS.update(p.acc.id, { fullName: name }); A.save(); } else A.ACCOUNTS.update(p.acc.id, { fullName: name, dateOfBirth: A.$('#profile-edit-birth').value || '', gender: A.$('#profile-edit-gender').value || '', address: (A.$('#profile-edit-address').value || '').trim() }); A.closeModal(); A.render(); U.toast('Đã cập nhật thông tin cá nhân.'); };
  A.ACT['profile-avatar-open'] = () => { const p = resolve(); if (p && p.mode === 'SELF') { ui.profileAvatarDraft = null; A.modal(avatarModal(null)); } };
  A.ACT['profile-avatar-choose'] = () => { const input = document.createElement('input'); input.type = 'file'; input.accept = 'image/jpeg,image/png,image/webp'; input.style.display = 'none'; document.body.appendChild(input); input.onchange = () => { const file = input.files && input.files[0]; input.remove(); if (!file) return; if (!/^image\/(jpeg|png|webp)$/.test(file.type) || file.size > 1024 * 1024) { U.toast('Chỉ hỗ trợ ảnh JPG, JPEG, PNG hoặc WEBP, tối đa 1 MB.'); return; } const reader = new FileReader(); reader.onload = () => { ui.profileAvatarDraft = { name: file.name, dataUrl: String(reader.result) }; A.modal(avatarModal(ui.profileAvatarDraft)); }; reader.readAsDataURL(file); }; input.click(); };
  A.ACT['profile-avatar-save'] = () => { const p = resolve(), draft = ui.profileAvatarDraft; if (!p || p.mode !== 'SELF' || !draft) return; if (p.trader) { p.trader.docFiles = p.trader.docFiles || {}; p.trader.docFiles.avatar = draft; A.save(); } else A.ACCOUNTS.update(p.acc.id, { avatar: draft }); ui.profileAvatarDraft = null; A.closeModal(); A.render(); U.toast('Đã cập nhật ảnh đại diện.'); };
  function requestModal(p) { return A.mHead('Yêu cầu thay đổi số điện thoại') + `<div class="modal-b profile-edit-modal"><div class="field"><label>Số hiện tại</label><input class="input" readonly value="${U.esc(p.phone)}"></div><div class="field"><label>Số điện thoại mới *</label><input id="phone-change-new" class="input" inputmode="tel" placeholder="Nhập số điện thoại mới"></div><div class="field"><label>Lý do thay đổi *</label><textarea id="phone-change-reason" class="input" rows="3"></textarea></div><div class="note info">Sau khi yêu cầu được phê duyệt, bạn cần xác minh số điện thoại mới bằng OTP trước khi thay đổi có hiệu lực.</div></div><div class="modal-f"><button class="btn" data-act="close">Hủy</button><button class="btn primary" data-act="phone-change-submit">Gửi yêu cầu</button></div>`; }
  function detailModal(r, admin) { const a = A.ACCOUNTS.get(r.accountId); const controls = admin && r.status === 'PENDING' ? '<button class="btn danger" data-act="phone-change-reject" data-id="' + r.id + '">Từ chối</button><button class="btn primary" data-act="phone-change-approve" data-id="' + r.id + '">Phê duyệt</button>' : ''; return A.mHead('Yêu cầu thay đổi số điện thoại') + `<div class="modal-b">${fieldList([['Người dùng', U.esc((a && a.fullName) || '')], ['Mã tài khoản', U.esc((a && a.code) || '')], ['Số hiện tại', U.esc(mask(r.oldPhone))], ['Số đề nghị', U.esc(mask(r.newPhone))], ['Lý do', U.esc(r.reason)], ['Ngày gửi', fmtTime(r.requestedAt)], ['Trạng thái', reqTag(r)], r.reviewNote ? ['Ghi chú xử lý', U.esc(r.reviewNote)] : null])}</div><div class="modal-f"><button class="btn" data-act="close">Đóng</button>${controls}</div>`; }
  function otpModal(r) { return A.mHead('Xác minh số điện thoại mới') + `<div class="modal-b profile-edit-modal"><p class="small muted">Mã OTP mô phỏng đã được gửi đến <b>${U.esc(mask(r.newPhone))}</b>.</p><div class="field"><label>Mã xác minh</label><input id="phone-change-otp" class="input" inputmode="numeric" maxlength="6" placeholder="Nhập 6 số OTP"></div></div><div class="modal-f"><button class="btn" data-act="close">Hủy</button><button class="btn primary" data-act="phone-change-complete" data-id="${r.id}">Xác nhận</button></div>`; }
  A.ACT['phone-change-open'] = () => { const p = resolve(); if (!p || p.mode !== 'SELF') return; if (ownRequest(p)) return U.toast('Bạn đang có yêu cầu thay đổi số điện thoại chưa hoàn tất.'); A.modal(requestModal(p)); };
  A.ACT['phone-change-submit'] = () => { const p = resolve(); if (!p || p.mode !== 'SELF' || ownRequest(p)) return; const raw = A.$('#phone-change-new').value, phone = A.ACCOUNTS.normalizePhone(raw), reason = (A.$('#phone-change-reason').value || '').trim(); if (!phoneOk(phone)) return U.toast('Vui lòng nhập số điện thoại gồm 10 chữ số, bắt đầu bằng 0.'); if (phone === A.ACCOUNTS.normalizePhone(p.acc.phone)) return U.toast('Số điện thoại mới phải khác số hiện tại.'); if (A.ACCOUNTS.byPhone(phone)) return U.toast('Số điện thoại này đã thuộc một tài khoản khác.'); if (!reason) return U.toast('Vui lòng nhập lý do thay đổi.'); const r = { id: 'SDT-' + U.pad(requests().length + 1, 4), accountId: p.acc.id, oldPhone: p.acc.phone, newPhone: phone, reason, status: 'PENDING', requestedAt: new Date().toISOString(), reviewedBy: null, reviewedAt: null, reviewNote: '', verifiedAt: null, completedAt: null }; requests().unshift(r); notify(null, 'Có yêu cầu thay đổi số điện thoại', 'Tài khoản ' + p.acc.code + ' đang chờ xử lý.'); A.save(); A.closeModal(); A.render(); U.toast('Đã gửi yêu cầu thay đổi số điện thoại.'); };
  A.ACT['phone-change-detail'] = el => { const p = resolve(), r = requests().find(x => x.id === el.dataset.id); if (p && r && (p.mode === 'SELF' ? r.accountId === p.acc.id : A.canDo('tai-khoan.sua'))) A.modal(detailModal(r, A.canDo('tai-khoan.sua'))); };
  A.ACT['phone-change-approve'] = el => { if (!A.canDo('tai-khoan.sua')) return; const r = requests().find(x => x.id === el.dataset.id); if (!r || r.status !== 'PENDING') return; r.status = 'APPROVED_PENDING_OTP'; r.reviewedBy = A.currentAccount().id; r.reviewedAt = new Date().toISOString(); notify(r.accountId, 'Yêu cầu thay đổi số điện thoại đã được phê duyệt', 'Vui lòng xác minh số điện thoại mới để hoàn tất.'); A.save(); A.closeModal(); A.render(); U.toast('Đã phê duyệt yêu cầu.'); };
  A.ACT['phone-change-reject'] = el => { if (!A.canDo('tai-khoan.sua')) return; const r = requests().find(x => x.id === el.dataset.id); if (!r || r.status !== 'PENDING') return; A.modal(A.mHead('Từ chối yêu cầu') + `<div class="modal-b"><div class="field"><label>Lý do từ chối *</label><textarea id="phone-change-reject-note" class="input" rows="3"></textarea></div></div><div class="modal-f"><button class="btn" data-act="close">Hủy</button><button class="btn danger" data-act="phone-change-reject-save" data-id="${r.id}">Từ chối</button></div>`); };
  A.ACT['phone-change-reject-save'] = el => { if (!A.canDo('tai-khoan.sua')) return; const r = requests().find(x => x.id === el.dataset.id), note = (A.$('#phone-change-reject-note').value || '').trim(); if (!r || r.status !== 'PENDING' || !note) return U.toast('Vui lòng nhập lý do từ chối.'); r.status = 'REJECTED'; r.reviewedBy = A.currentAccount().id; r.reviewedAt = new Date().toISOString(); r.reviewNote = note; notify(r.accountId, 'Yêu cầu thay đổi số điện thoại không được chấp thuận', note); A.save(); A.closeModal(); A.render(); };
  A.ACT['phone-change-verify'] = el => { const p = resolve(), r = requests().find(x => x.id === el.dataset.id); if (p && p.mode === 'SELF' && r && r.accountId === p.acc.id && r.status === 'APPROVED_PENDING_OTP') A.modal(otpModal(r)); };
  A.ACT['phone-change-complete'] = el => { const p = resolve(), r = requests().find(x => x.id === el.dataset.id); if (!p || p.mode !== 'SELF' || !r || r.accountId !== p.acc.id || r.status !== 'APPROVED_PENDING_OTP') return; if ((A.$('#phone-change-otp').value || '') !== '123456') return U.toast('Mã OTP không chính xác.'); if (A.ACCOUNTS.byPhone(r.newPhone)) return U.toast('Số điện thoại mới đã được sử dụng.'); A.ACCOUNTS.update(p.acc.id, { phone: r.newPhone }); r.status = 'COMPLETED'; r.verifiedAt = r.completedAt = new Date().toISOString(); notify(p.acc.id, 'Thay đổi số điện thoại thành công', 'Vui lòng đăng nhập lại bằng số điện thoại mới.'); A.save(); A.closeModal(); U.toast('Thay đổi số điện thoại thành công. Vui lòng đăng nhập lại.'); A.ACT['auth-logout'](); };
  A.phoneChangeAdminSummaryHtml = function () { if (!A.canDo('tai-khoan.sua')) return ''; const n = requests().filter(r => r.status === 'PENDING').length; return `<div class="card acc-phone-requests"><div><b>Yêu cầu thay đổi số điện thoại</b><div class="small muted">${n ? n + ' yêu cầu đang chờ xử lý' : 'Không có yêu cầu chờ xử lý'}</div></div>${n ? '<button class="btn sm" data-act="phone-change-admin-list">Xem & xử lý</button>' : ''}</div>`; };
  A.phoneChangeAdminOpenButton = id => A.canDo('tai-khoan.sua') ? `<button class="btn sm" data-act="phone-change-admin-list" data-account="${id}">Quản lý yêu cầu thay đổi</button>` : '';
  A.ACT['phone-change-admin-list'] = el => { if (!A.canDo('tai-khoan.sua')) return; const rs = requests().filter(r => !el.dataset.account || r.accountId === el.dataset.account); A.modal(A.mHead('Yêu cầu thay đổi số điện thoại') + `<div class="modal-b"><div class="tbl-wrap"><table class="tbl"><thead><tr><th>Người dùng</th><th>Số mới</th><th>Ngày gửi</th><th>Trạng thái</th><th></th></tr></thead><tbody>${rs.map(r => { const a = A.ACCOUNTS.get(r.accountId); return `<tr><td>${U.esc((a && a.fullName) || '')}</td><td>${U.esc(mask(r.newPhone))}</td><td>${fmtTime(r.requestedAt)}</td><td>${reqTag(r)}</td><td><button class="btn sm" data-act="phone-change-admin-detail" data-id="${r.id}">Xem</button></td></tr>`; }).join('') || '<tr><td colspan="5" class="muted">Chưa có yêu cầu.</td></tr>'}</tbody></table></div></div><div class="modal-f"><button class="btn" data-act="close">Đóng</button></div>`); };
  A.ACT['phone-change-admin-detail'] = el => { if (!A.canDo('tai-khoan.sua')) return; const r = requests().find(x => x.id === el.dataset.id); if (r) A.modal(detailModal(r, true)); };
})(window.APP);
